### ISSUE TITLE
[BUG] bbox_to_string has wrong description

### ISSUE THREAD

**Issue by RegularnaMatrica** [ropensci/osmdata#267] opened 2022-02-16 07:34 UTC
`A character string representing min x, min y, max x, and max y bounds`

![image](https://user-images.githubusercontent.com/65914613/154217282-52fef6e0-d11b-4da5-bb1b-f8b1741e1038.png)

`bbox_to_string` does y before x.

**Comment by mpadge** [comment] 2022-02-16 08:27
This is expected behaviour and not a bug, because that is [how Overpass defines bounding boxes](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Global_bounding_box_.28bbox.29). y always comes before x. Please close the issue unless you think there is anything else awry here. Thanks

**Closed** 2022-02-16 08:47 UTC
