### ISSUE TITLE
[BUG] Support for language special characters

### ISSUE THREAD

**Issue by GitHunter0** [ropensci/osmdata#275] opened 2022-08-09 19:38 UTC
The package is returning data with unrecognizable characters, in the example below, it should return German words but it instead returned strings like this `Michael-BrÃ¼ckner-StraÃŸe`. Please, is there a way to configure for the correct character encoding?

**Steps to follow in reporting a bug with `osmdata`**

Please follow all of the following steps, and only submit once you've checked all boxes (where appropriate).

- [ ] Download data locally via `osmdata_xml(q, filename = "myfile.xml")` (where `q` is your query)
- [x] Use the [`reprex` package](https://reprex.tidyverse.org/) to reproduce your bug, including a `setwd()` command at the start to ensure you are in the directory where you've downloaded your data
- [ ] Include comparison with equivalent results from the `sf` package using the code shown below
- [x] Paste the result in the indicated section below
- [ ] Delete the `setwd()` line from the pasted result
- [x] Include the output of both `packageVersion("osmdata")` and `R.Version()$version.string`
- [x] Alternatively, include the full output of `sessionInfo()`

``` r
library(osmdata)
#> Warning: package 'osmdata' was built under R version 4.1.3
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright

berlin_bbox <- osmdata::getbb("Berlin, Germany")

berlin_highways_sf <- osmdata::opq(berlin_bbox) |> 
    osmdata::add_osm_feature(
        key   = "highway", 
        value = c("motorway", "primary", "motorway_link", "primary_link")
    ) |> 
    osmdata::osmdata_sf() 

berlin_highways_sf
#> Object of class 'osmdata' with:
#>                  $bbox : 52.3382448,13.088345,52.6755087,13.7611609
#>         $overpass_call : The call submitted to the overpass API
#>                  $meta : metadata including timestamp and version numbers
#>            $osm_points : 'sf' Simple Features Collection with 22146 points
#>             $osm_lines : 'sf' Simple Features Collection with 5584 linestrings
#>          $osm_polygons : 'sf' Simple Features Collection with 2 polygons
#>        $osm_multilines : 'sf' Simple Features Collection with 3 multilinestrings
#>     $osm_multipolygons : NULL

berlin_highways_sf$osm_lines$name |> head()
#> [1] "Frankfurter Allee"         "Michael-BrÃ¼ckner-StraÃŸe"
#> [3] "Ã–stlicher Berliner Ring"  NA                         
#> [5] "MÃ¼llerstraÃŸe"            NA
```

<sup>Created on 2022-08-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

``` r
packageVersion("osmdata")
#> [1] '0.1.10'
R.Version()$version.string
#> [1] "R version 4.1.1 (2021-08-10)"
sessionInfo()
#> R version 4.1.1 (2021-08-10)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19044)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] rstudioapi_0.13   knitr_1.39        magrittr_2.0.3    R.cache_0.16.0   
#>  [5] rlang_1.0.4       fastmap_1.1.0     fansi_1.0.3       stringr_1.4.0    
#>  [9] styler_1.7.0      highr_0.9         tools_4.1.1       xfun_0.31        
#> [13] R.oo_1.24.0       utf8_1.2.2        cli_3.3.0         withr_2.5.0      
#> [17] htmltools_0.5.2   ellipsis_0.3.2    yaml_2.3.5        digest_0.6.29    
#> [21] tibble_3.1.7      lifecycle_1.0.1   crayon_1.5.1      purrr_0.3.4      
#> [25] R.utils_2.11.0    vctrs_0.4.1       fs_1.5.2          glue_1.6.2       
#> [29] evaluate_0.15     rmarkdown_2.11    reprex_2.0.1      stringi_1.7.6    
#> [33] compiler_4.1.1    pillar_1.7.0      R.methodsS3_1.8.1 pkgconfig_2.0.3
```

<sup>Created on 2022-08-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mpadge** [comment] 2022-08-09 19:57
That is caused by your own system-specific encoding, and not by this package. Here is what I see - and what you should see once you figure out how to set up your encoding:

``` r
library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
berlin_bbox <- osmdata::getbb("Berlin, Germany")

berlin_highways_sf <- osmdata::opq(berlin_bbox) |> 
    osmdata::add_osm_feature(key   = "highway", 
                             value = c("motorway", "primary", "motorway_link", "primary_link")
                             ) |> 
    osmdata::osmdata_sf() 

berlin_highways_sf$osm_lines$name |> head()
#> [1] "Frankfurter Allee"       "Michael-Brückner-Straße"
#> [3] "Östlicher Berliner Ring" NA                       
#> [5] "Müllerstraße"            NA
```

<sup>Created on 2022-08-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

A good starting point to understanding how to configure encoding in R is ["String Encoding and R" by Kevin Ushey](https://kevinushey.github.io/blog/2018/02/21/string-encoding-and-r/). I'm going to close this, but feel free to ask here if you run into further issues.

**Closed by mpadge** 2022-08-09 19:57 UTC
