### ISSUE TITLE
Fails to download closed loop roads

### ISSUE THREAD

**Issue by mem48** [ropensci/osmdata#103] opened 2017-10-26 11:02 UTC
I've noticed that when using osmdata that often roundabouts and closed loops in the road network do not get downloaded.

Example

```
library(sf)
library(osmdata)
library(tmap) # Only Needed For Visualisation
tmap_mode("view")

# Example Location
box = st_sfc(st_polygon(list(rbind(c(-2.569,51.493),c(-2.554,51.493),c(-2.554,51.487),c( -2.569,51.487),c(-2.569,51.493)))))

# Get Highway Data from OSM
q = opq(st_bbox(box)) %>%
  add_osm_feature(key = "highway")
res = osmdata_sf(q = q)

lines = res$osm_lines
qtm(lines)
```

In this location, there are three loop roads that are missing from the lines data.

![rplot](https://user-images.githubusercontent.com/15819577/32049602-88b138cc-ba45-11e7-999d-064cb07d403c.png)

**Comment by mpadge** [comment] 2017-10-26 11:24
Thanks, I'll check it out and get back to you

**Comment by mpadge** [comment] 2017-10-27 11:59
Aha, that's actually just because these closed ways are polygons according to Simple Features geometric definitions. They are simply in `$osm_polygons` rather than `$osm_lines`
```
> as.character (names (res$osm_polygons))
[1] "Gainsborough Square" "Turner Gardens"      "Copley Gardens" 
```
And there they are. `tmap::qtm()` only accepts objects of one single class, so you still can't plot both simultaneously, but that is unfortunately a separate issue that can't be address within `osmdata`. You could try coercing the polygons into lines?

**Comment by Robinlovelace** [comment] 2017-10-27 13:54
I thought it was something like that! Malcolm said they weren't in the polygons. I think an a function to convert polygons marked as ways would solve the issue for me (still don't think it's fixed from a user's perspective but shouldn't be to much work - @mem48 and I could take a look...).

**Comment by mpadge** [comment] 2017-10-27 14:14
Yeah, because so many mapping tools like `qtm` just accept a line `line` **OR** `polygon` structure, there really does need to be a way to coerce the latter to the former. It shouldn't be too hard. As always, most pressing Q is likely to be where such a function would be live. It directly contradicts OGC SF standards, and so would be unacceptable in `sf` as well, but damn practical nonetheless. Maybe i'll re-open this issue as a prompt to act on this larger issue, and leave it until we find a more appropriate place to implement it.

**Comment by Robinlovelace** [comment] 2017-10-27 14:47
In this pkg would be the logical place. On a related note I think there are loads of general transport funs that could go in stplanr but wanted to check with you first. Another one to discuss.

**Comment by mem48** [comment] 2017-10-30 20:02
So I've been looking into this, and it is not a simple as I thought. `add_osm_feature(key = "highway")` doesn't seem to remove all the non-highway polygons so I'm getting things like fountains, service stations etc, which can be walked on but are not roads.

**Comment by mem48** [comment] 2017-10-30 20:15
So far I've found this seems to work:

```
lines.loops <- res$osm_polygons
lines.loops <- lines.loops[!is.na(lines.loops$highway),]
lines.loops <- lines.loops[is.na(lines.loops$area),]
lines.loops <- st_cast(lines.loops, "LINESTRING")
```

**Comment by mpadge** [comment] 2017-10-30 20:19
Can you provide some reproducible code please? The previous example only gave three polygons, and they were all enclosed highways, so that should just work. Are you now working with different test data?

**Comment by mem48** [comment] 2017-10-30 20:34
```
library(sf)
library(osmdata)
library(tmap) # Only Needed For Visualisation
tmap_mode("view")

# Example Location
box = st_sfc(st_polygon(list(rbind(c(-2.755,51.493),c(-2.510,51.493),c(-2.510,51.397),c(-2.755,51.397),c(-2.755,51.493)))))

# Get Highway Data from OSM
q = opq(st_bbox(box)) %>%
  add_osm_feature(key = "highway")
res = osmdata_sf(q = q)

lines.loops = res$osm_polygons

#Split out the false results
f1 <- lines.loops[is.na(lines.loops$highway),]

qtm(f1, fill = "red")
```

**Comment by mpadge** [comment] 2017-10-30 21:09
It all works perfectly:
```
library(osmdata)
library (magrittr)

# Example Location
box <- c (-2.569, 51.487, -2.554, 51.493) # original zoomed-in bit around Gainsborough Sq.

res = opq(box) %>%
      add_osm_feature(key = "highway") %>%
      osmdata_sf()

hwys <- res$osm_lines
hwy.loops = res$osm_polygons

hwy.loops <- st_cast (hwy.loops, "LINESTRING")
hwys <- rbind (hwys, hwy.loops)
```
This does not work:
```
library(tmap) # Only Needed For Visualisation
tmap_mode("view")
qtm(hwys, lines.col = "red")
```
But this works perfectly:
```
library (osmplotr)
osm_basemap (bbox = matrix (box, nrow = 2)) %>%
    add_osm_objects (hwys) %>%
    print_osm_map ()
```
![map](https://user-images.githubusercontent.com/6697851/32195659-2f767426-bdbe-11e7-99c2-6f3475176a21.png)

All circular highways are there. So the whole issue is as simple as `sf::st_cast()`. `osmdata` is intentionally `sf` independent, but `sf_cast` in this case just renames the `POLYGON` geometries to `LINESTRING` and moves them up one step in the list hierarchy. Totally easy to implement, but also possible not really worthwhile because:
1. It's utterly simple for anyone to just `st_cast` for themselves; but more importantly:
2. Your larger example shows the unavoidable necessity of prior data cleaning, which is unavoidable and far more work than the handful of lines that such as ostensible function would be.

My suggestion would be just to put a simple description of the general process in the vignette rather than implement another function. Thoughts @mem48 @Robinlovelace?

**Comment by Robinlovelace** [comment] 2017-10-31 08:32
I think that highways as polygons is common enough to merit a separate argument in `osmdata_sf()` etc. I would call it `highways_as_lines` or similar to avoid any ambiguity.

**Comment by Robinlovelace** [comment] 2017-10-31 08:34
Btw I think the **tmap** and **sf** plotting functions *do* show the polygon-line, as illustrated below:

``` r
library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.2.1, proj.4 4.9.2, lwgeom 2.3.3 r15473
library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright
library(magrittr)

# Example Location
box <- c(-2.569, 51.487, -2.554, 51.493)  # original zoomed-in bit around Gainsborough Sq.

res = opq(box) %>% add_osm_feature(key = "highway") %>% osmdata_sf()

hwys <- res$osm_lines
hwy.loops = res$osm_polygons

hwy.loops <- st_cast(hwy.loops, "LINESTRING")
#> Warning in st_cast.sf(hwy.loops, "LINESTRING"): repeating attributes for
#> all sub-geometries for which they may not be constant
hwys <- rbind(hwys, hwy.loops)
plot(res$osm_lines$geometry, col = "red", lwd = 3)
plot(hwys$geometry, add = TRUE)
```

![](https://i.imgur.com/bn5RPWk.png)

``` r

library(tmap)  # Only Needed For Visualisation
tmap_mode("view")
#> tmap mode set to interactive viewing
qtm(hwys, lines.col = "red")
```

![](https://i.imgur.com/urSdy9R.png)

``` r
library(osmplotr)
#> Error in library(osmplotr): there is no package called 'osmplotr'

osm_basemap(bbox = matrix(box, nrow = 2)) %>% add_osm_objects(hwys) %>% print_osm_map()
#> Error in osm_basemap(bbox = matrix(box, nrow = 2)): could not find function "osm_basemap"
```

**Comment by mpadge** [comment] 2017-10-31 09:39
huh, you're right `tmap` does work. When I first ran it yesterday, it gave really strange results. But all good. So okay, let's incorporate a new function. I make the following observations:
1. The return structure of `osmdata_sf/sp` reflects an attempt at the truly optimal compromise between the in-many-ways irreconcilable spatial representations of OSM and Simple Features, as detailed in the [second vignette](https://ropensci.github.io/osmdata/articles/osm-sf-translation.html). The primary aim of the `osmdata` package is faithful data representation in R, and I would be loathe to add extra parameters that modified that structure.
2. `osmplotr` is in the process of developing an `osm_lines2poly()` function thanks to @richardbeare. That is also borne of plotting necessity in cases where lines delineate solid regions, yet don't necessarily form polygons. Coastlines are the classic example. `osm_lines2poly()` closes those lines by forming polygons around the perimeter of a given plot region.
3. The proposed function is effectively the reverse of that, `osm_poly2lines()`. I guess the only odd thing is that `osm_lines2poly()` would live in `osmplotr` - the only rightful place for that - while `osm_poly2line()` would live in `osmdata`. The latter function really is only borne of the necessity to compromise in order to meet the expectations of other plotting routines, most of which expect or can plot objects of only one single type. It is thus also nothing more than a convenience function for plotting, yet not one that needs to reside in `osmplotr`, because that has no problems plotting multiple object types. I guess `osmdata` is therefore an appropriate place.

Further thoughts?

**Comment by mem48** [comment] 2017-10-31 17:16
New problem this is a polygon with a highway tag, but is just an area not a road

```
library(sf)
library(osmdata)
library(tmap) # Only Needed For Visualisation
tmap_mode("view")

# Example Location
box = st_sfc(st_polygon(list(rbind(c(-2.711,51.479),c(-2.701,51.479),c(-2.701,51.474),c(-2.711,51.474),c(-2.711,51.479)))))

# Get Highway Data from OSM
q = opq(st_bbox(box)) %>%
  add_osm_feature(key = "highway")
res = osmdata_sf(q = q)

lines.loops = res$osm_polygons
qtm(lines.loops)
```

**Comment by mpadge** [comment] 2017-10-31 18:27
Checking it out now, but note that the `bbox` arg for `opq` can be a simple vector, so you can just
```
box <- c (-2.711, 51.474, -2.701, 51.479)
q <- opq (box)
```
and ditch all the `sf` guff

**Comment by mpadge** [comment] 2017-10-31 18:36
OSM allows [`highway = services`](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dservices) for exactly this purposes of delineating truck stops like [the one you've got there](http://www.openstreetmap.org/#map=17/51.47721/-2.70721). These are an integral part of highway systems, and so are appropriately tagged as highways.

**Comment by mpadge** [comment] 2017-11-02 09:30
@mem48 @Robinlovelace Actually this function is critically necessary, because the [`dodgr` package](https://github.com/gmost/dodgr) routes through the `osmdata$osm_lines` component only, and so will also miss all off these ways that just happen to connect at the ends. I'm on it right now ... Thanks @mem48 for the heads up here! Very helpful indeed!

**Comment by Robinlovelace** [comment] 2017-11-02 09:40
Glad it's been of use - may lead to a decrease in 'citydists' in roundabout-happy cities!

**Comment by mpadge** [comment] 2017-11-02 15:10
New `osm_line2poly()` function added with [this commit](https://github.com/ropensci/osmdata/commit/0646b5e55c240c4369951a3ba3433e6657b4ad88). All read to use:
```
res <- opq (bbox) %>% add_osm_feature (key = "highway") %>%
    osmdata_sf() %>% osm_line2poly ()
```
That will return an `osmdata` object in which all polygons have been converted to lines and appended to the `osm_lines` item (they are also kept in original polygon format in `osm_polygons`).

Issue to kept open until proper examples and tests have been written

**Closed** 2017-11-02 15:28 UTC
